# Generated by Django 3.2 on 2023-06-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childdetails',
            options={'verbose_name_plural': 'ChildDetails'},
        ),
    ]
